runtime: nodejs16
instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  target_cpu_utilization: 0.95
  target_throughput_utilization: 0.95
  max_concurrent_requests: 80
env_variables:
  SLACK_BOT_TOKEN: "$SLACK_BOT_TOKEN"
  SLACK_SIGNING_SECRET: "$SLACK_SIGNING_SECRET"
  NOTION_API_TOKEN: "$NOTION_API_TOKEN"
  NOTION_TASK_DATABASE_ID: "$NOTION_TASK_DATABASE_ID"
  NOTION_BLOG_DATABASE_ID: "$NOTION_BLOG_DATABASE_ID"
  GH_TOKEN: "$GH_TOKEN"