name: Deploy to Google App Engine

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Post Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "SlackApp Deployment started (In Progress)",
              "attachments": [
                {
                  "pretext": "Deployment started",
                  "color": "ffc107",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
      - name: Replace credentials in app.yaml v1
        run: |
          sed -i -e 's/$SLACK_BOT_TOKEN/${{ secrets.SLACK_BOT_TOKEN }}/g' app.yaml
          sed -i -e 's/$SLACK_SIGNING_SECRET/${{ secrets.SLACK_SIGNING_SECRET }}/g' app.yaml
          sed -i -e 's/$NOTION_API_TOKEN/${{ secrets.NOTION_API_TOKEN }}/g' app.yaml
          sed -i -e 's/$GH_TOKEN/${{ secrets.GH_TOKEN }}/g' app.yaml
          sed -i -e 's/$TWITTER_API_KEY/${{ secrets.TWITTER_API_KEY }}/g' app.yaml
          sed -i -e 's/$TWITTER_API_SECRET/${{ secrets.TWITTER_API_SECRET }}/g' app.yaml
          sed -i -e 's/$TWITTER_ACCESS_TOKEN/${{ secrets.TWITTER_ACCESS_TOKEN }}/g' app.yaml
          sed -i -e 's/$TWITTER_ACCESS_SECRET/${{ secrets.TWITTER_ACCESS_SECRET }}/g' app.yaml
          sed -i -e 's/$CORPORATE_SITE_URL/${{ secrets.CORPORATE_SITE_URL }}/g' app.yaml
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          version: v1
      - name: Update Slack message if deployment is failed
        if: failure()
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "SlackApp Deployment failed",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "dc3545",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Failed"
                    }
                  ]
                }
              ]
            }
      - name: Update Slack message if deployment is successful
        if: success()
        uses: slackapi/slack-github-action@v1.23.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "SlackApp Deployment succeeded",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Success"
                    }
                  ]
                }
              ]
            }