name: Deploy to Google App Engine

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Replace credentials in app.yaml
        run: |
          sed -i -e 's/$SLACK_BOT_TOKEN/${{ secrets.SLACK_BOT_TOKEN }}/g' app.yaml
          sed -i -e 's/$SLACK_SIGNING_SECRET/${{ secrets.SLACK_SIGNING_SECRET }}/g' app.yaml
          sed -i -e 's/$NOTION_API_TOKEN/${{ secrets.NOTION_API_TOKEN }}/g' app.yaml
          sed -i -e 's/$GH_TOKEN/${{ secrets.GH_TOKEN }}/g' app.yaml
          sed -i -e 's/$TWITTER_API_KEY/${{ secrets.TWITTER_API_KEY }}/g' app.yaml
          sed -i -e 's/$TWITTER_API_SECRET/${{ secrets.TWITTER_API_SECRET }}/g' app.yaml
          sed -i -e 's/$TWITTER_ACCESS_TOKEN/${{ secrets.TWITTER_ACCESS_TOKEN }}/g' app.yaml
          sed -i -e 's/$TWITTER_ACCESS_SECRET/${{ secrets.TWITTER_ACCESS_SECRET }}/g' app.yaml
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.3.1
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
      - name: Notify deployment
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()